name: Elspeth Gow
author: Elspeth Gow
baseurl: /HIST487
description: History 487 Course Outline

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "index.md"
      type: "pages"
    values:
      layout: "index"
