name: Elspeth Gow
author: Elspeth Gow
baseurl: /HIST487
description: History 487 Course Outline
land: This class takes place on the traditional, ancestral, and unceded territory of the Musqueam people.

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "index.md"
      type: "pages"
    values:
      layout: "index"
